dist: xenial

language: r

r: release

matrix:
  include:
  - os: linux
    env: PYENV=py37
  - os: osx
    env: PYENV=py37
# turn these on once travis support gets a little better, see pyam for example
#  - os: windows
#    env: PYENV=py37

r_packages:
- IRkernel

cache:
  # Travis ensures these directories are created if they do not already exist
  directories:
  - $HOME/.conda/pkgs
  - $HOME/.cache/ixmp
  - $HOME/R/Library

addons:
  apt:
    packages:
    - graphviz
  homebrew:
    packages:
    - graphviz

before_install:
  - source ci/env.sh
  - source ci/travis-before_install.sh

install:
  - source ci/travis-install.sh
  - pip install .[docs,tests,tutorial]
  - Rscript -e 'devtools::install("rixmp", dep = T)'

script:
  - python -c "import os, sys; assert os.environ['PYVERSION'] == sys.version[0]"
  # Run tests
  # These include the equivalent of Travis R tests via test_r.py
  - >
    pytest
    --testr
    --verbose
    --cov=ixmp
    --cov-config ci/.coveragerc
    --cov-report term-missing
  # Test that documentation can be built
  - cd doc
  - pip install -r requirements.txt
  - make html

after_success:
  - coverage combine
  - codecov
