# Continuous integration configuration for Travis
# NB use https://config.travis-ci.com/explore to validate changes

branches:
  only:
  - master
  - 2.0.x

dist: xenial

language: r

r: release

# - Build against Python 3.7
# - Always display verbose exceptions in JDBCBackend
env:
  PYENV=py37
  IXMP_JDBC_EXCEPTION_VERBOSE=1

os:
- linux
- osx
# TODO turn this on once Travis Windows support improves
# - windows

r_packages:
- IRkernel

cache:
  # Travis ensures these directories are created if they do not already exist
  directories:
  - $HOME/.conda/pkgs
  - $HOME/.cache/ixmp
  - $HOME/R/Library

addons:
  apt:
    packages:
    - graphviz
  homebrew:
    packages:
    - graphviz

before_install:
  # Set other environment variables
  - source ci/env.sh
  # Download GAMS and Miniconda
  - source ci/travis-before_install.sh

install:
  # Install GAMS, conda, Python dependencies, and R packages needed for testing
  - source ci/travis-install.sh
  # Install the Python package
  - pip install --editable .[docs,tests,tutorial]
  # Install the R package
  - Rscript -e "devtools::install('rixmp')"

script:
  - python -c "import os, sys; assert os.environ['PYVERSION'] == sys.version[0]"
  # Run tests. These include the equivalent of Travis R tests via test_r.py.
  - pytest ixmp -m 'rixmp or not performance' --verbose --cov-report=xml
  # Test that documentation can be built
  - cd doc
  - pip install -r requirements.txt
  - make html

after_success:
  - codecov
