name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # For setuptools-scm. With fetch --tags below, this ensures that
  # enough history is fetched to contain the latest tag, so that
  # setuptools-scm can generate the version number. Update:
  # - See https://github.com/iiasa/ixmp/releases, at "NN commits to
  #   master since this release". The value should be at least equal to
  #   NN + the number of commits on any PR branch.
  # - Reset to a lower value, e.g. 100, after a new release.
  depth: 100

jobs:
  lint:
    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ${{ env.depth }}

    - name: Fetch tags (for setuptools-scm)
      run: git fetch --tags --depth=${{ env.depth }}

    - uses: actions/setup-python@v2

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/Library/Caches/pip
          ~/appdata/local/pip/cache
        key: lint-${{ runner.os }}

    - name: Upgrade pip, wheel, setuptools-scm
      run: python -m pip install --upgrade pip wheel setuptools-scm

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --count --max-complexity=29 --show-source --statistics

    - name: Test package build
      run: |
        pip install twine wheel
        python3 setup.py bdist_wheel sdist
        twine check dist/*

    - name: Test documentation build
      run: |
        pip install .[docs,tests,tutorial]
        make --directory=doc html
