name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: iiasa/actions/.github/workflows/lint.yaml@main
    with:
      type-hint-packages: >-
        genno
        GitPython
        nbclient
        pytest
        sphinx
        xarray
